### ISSUE TITLE
Crash report + request for install instructions

### ISSUE THREAD

**Issue by alizehctl** [BenediktMagnus/kimai-gnome-shell-extension#1]
Hi! So I cloned your extension to `~/.local/share/gnome-shell/extensions/kimai@benediktmagnus.de` and restarted GNOME.

Was about to start configuring the extension but was greeted by a crash report in extension manager:

The settings of extension kimai@benediktmagnus.de had an error:
```
GLib.FileError: Failed to open file “/home/aadil/.local/share/gnome-shell/extensions/kimai@benediktmagnus.de/schemas/gschemas.compiled”: open() failed: No such file or directory
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:200:31
fillPreferencesWindow@/home/aadil/.local/share/gnome-shell/extensions/kimai@benediktmagnus.de/prefs.js:20:37
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Is there something I did wrong? I'm running the extension on Pop!_OS 22.04, which uses GNOME 42.

**Comment by BenediktMagnus** [comment]
Hi aadilayub!

Thank you for the report.

For an installation from source, you need to compile the schemas: `glib-compile-schemas schemas/` (inside the cloned extension folder). I have added an installation instruction to the readme to clarify this in the future.
Let me know whether this solves your issue or not.
